openapi: 3.0.3
info:
  title: sunflower
  description: |
    sunflower 服务发现提供 API。 | 表示换行，< 表示忽略换行。
  version: "1.0.0"
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: API Support
    url: http://www.example.com/support
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: service
    description: 服务注册和发现
servers:
  - url: 'http://127.0.0.1'

paths:
  /api/v1/service/register/{dc}/{ns}:
    post:
      tags:
        - service
      summary: 注册一个新的服务，如果服务已经存在则替换
      description: 注册一个新的服务，如果服务已经存在则替换
      parameters:
        - name: dc
          in: path
          description: 数据中心 默认值 default
          example: default
        - name: ns
          in: path
          description: 命名空间 namespace
          example: default
      requestBody:
        description: 需要被添加进商店的 Pet 对象
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Server'
      responses:
        "200":
          description: "成功"

components:
  schemas:
    Server:
      type: object
      required:
        - instanceId
        - serviceName
        - host
      properties:
        instanceId:
          type: string
          description: 服务实例Id, 需全局唯一
        serviceId:
          type: string
          description: 服务 id
        host:
          type: string
          description: ip 或者域名
          example: 127.0.0.1
        port:
          type: integer
          description: 端口号
          example: 8080
          default: 80
        metadata:
          type: object
          properties: { }
